services:
  client:
    build:
      context: .
      dockerfile: ./docker/dev/client/Dockerfile
  server:
    build:
      context: .
      dockerfile: ./docker/dev/client/Dockerfile
  generator:
    build:
      context: .
      dockerfile: ./docker/dev/generator/Dockerfile
